### ISSUE TITLE
sync.register when permission is denied

### ISSUE THREAD

**Issue by jkarlin** [WICG/BackgroundSync#122] opened 2016-02-05 14:00 UTC
If Background Sync were to be added to the permissions API, what should `sync.register`'s behavior be when sync permission is denied?

**Reject the registration**
This is the simplest approach. If permission is denied then simply reject the registration.
- Simple and expected by developers
- Developer needs an alternate upload handler in case of rejection. 

**Resolve the registration but don't run in the background**
Background sync will work as usual so long as it's not [in the background](https://wicg.github.io/BackgroundSync/spec/#in-the-background). The `register` call should probably return a boolean on whether it will run in the background or not. 

- Unexpected behavior for developers given that it's called "background sync". 
- Single method of uploading data with retries.

**Comment by beverloo** [comment] 2016-02-05 16:44
It feels to me like rejecting the `register()` promise with a `PermissionDeniedError` would both be clear and consistent with other APIs. What I'm concerned about a little bit is that, despite the examples, developers might not gracefully handle the rejection case because in practice it shouldn't happen when used from a document.

In the second option, I guess the implementation would hold on to sync and execute it the next time the user visits the page? As a developer, if I were to get a `false` value I'd probably want to try to send an XHR regardless— next usage could be far away.

An additional downside of resolving the `register()` promise with a boolean is that it'll take away our option of returning a `SyncRegistration` object of sorts, and make future attempts to have `unregister()` or a `finished` promise a bit more awkward (you'd have to go through a `getRegistrations()`).

**Comment by mkruisselbrink** [comment] 2016-02-05 17:36
A third alternative might be to make the behavior depend on the current online state; if the user agent is online when `register()` is called, immediately fire a sync event with lastChance = true, but if the user agent is not online, reject the `register()` call. That has the benefit that the developer can still use background sync and the service worker to do the actual sync, but we don't enable anything that wouldn't already be available in the absence of background sync (since the register() always happens when not in the background, this is a variation of the second option, without the need to have a boolean return value).

**Comment by martinthomson** [comment] 2016-02-06 02:32
I like @mkriusselbrink's idea. The idea that this might still work without permissions is odd, but appropriate in this case. I suspect that we will have to get to a point where we don't prompt for this api anyway.

**Comment by nicolassatragno** [comment] 2016-02-08 11:25
Deciding on one of the alternatives defines the scope of background sync. Since the spec states that the mission of background sync is precisely enabling web applications to synchronize data _in the background_, it makes sense to reject the promise in every case (assuming the user blocked permission). As mentioned, we already have powerful mechanisms to send requests while the browser is online.

A developer could easily abstract away the upload method, switching to a new upload strategy if the promise is denied. This is a natural, graceful degradation.
```javascript
reg.sync.register('send-chats')
   .then( ... )
   .catch(() => {
      // No background sync capabilities, maybe tell user.
      fromNowOnUseAnotherUploadMethod();
});
```
If we go with the "Resolve the registration but don't run in the background" approach then the developer may be confused about why we sometimes reject the registration for the same user. They would also be basically catching a connection error when registering sync, which feels out of place.

**Comment by jkarlin** [comment] 2016-02-10 13:07
I'm inclined to agree with @nicolassatragno . I think it's confusing to have two behaviors, one of which has nothing to do with syncing in the background. If we resolve if online and fire once, it will only encourage developers not to check for rejections. I also think it's important that the permission behavior is in line with other APIs, such as Push.

I'd like to get more opinions here though. What are your thoughts @domenic, @slightlyoff , @jakearchibald, @annevk ?

**Comment by jakearchibald** [comment] 2016-02-11 11:52
The problem with rejecting is "will developers bother to handle that case?", and although @mkruisselbrink's solution is nifty it's making the rejection case more obscure, therefore less chance developers will handle it.

Rejecting feels like the right thing to do, we just need to do a good job of informing developers that they need to handle register rejections. In a future serviceworker-everywhere utopia this becomes fairly easy:

```js
// page.js
sendButton.on('click', () => {
  addToOutbox();
  navigator.serviceWorker.ready.then(reg => {
    reg.sync.register('outbox').catch(() => {
      reg.active.postMessage('sync-outbox');
    });
  });
});
```

```js
// sw.js
function performOutboxSync(lastChance) {
  return new Promise(…);
}

self.addEventListener('sync', event => {
  if (event.tag == 'outbox') {
    event.waitUntil(performOutboxSync(event.lastChance));
  }
});

self.addEventListener('message', event => {
  if (event.data == 'sync-outbox') {
    event.waitUntil(performOutboxSync(true));
  }
});
```

**Comment by annevk** [comment] 2016-02-11 14:17
Is rejection the exceptional case here? That is, are developers expected to guard this call somehow? @jakearchibald does not seem to do that above which means that the code might become somewhat ugly with async/await syntax (you'd have to use try/catch there).

**Comment by domenic** [comment] 2016-02-11 14:23
> Unexpected behavior for developers given that it's called "background sync". 

This doesn't seem correct. The developer facing API is `reg.sync`, not `reg.backgroundSync`. As long as some syncing happens, I think it should fulfill.

It does also seem the case that registration failing is not exceptional (in general users denying permission is not exceptional).

> An additional downside of resolving the register() promise with a boolean is that it'll take away our option of returning a SyncRegistration object of sorts

In general I do agree returning a boolean is not a great idea. Even just an object like `{ canSyncInBackground: false }` (or some shorter name) would make more sense to me. Maybe that is part of the SyncRegistration object, but I haven't studied the spec enough to be sure.

**Comment by jkarlin** [comment] 2016-02-11 14:57
> This doesn't seem correct. The developer facing API is reg.sync, not reg.backgroundSync. As long as some syncing happens, I think it should fulfill.

Syncing may not happen if the page disappears before sync is fired.

> It does also seem the case that registration failing is not exceptional (in general users denying permission is not exceptional).

This is strange to me. Push rejects if permission is denied. The [TAG promises guide](https://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional) suggests that denied permission is a good case for rejection.

> In general I do agree returning a boolean is not a great idea. Even just an object like { canSyncInBackground: false } (or some shorter name) would make more sense to me. Maybe that is part of the SyncRegistration object, but I haven't studied the spec enough to be sure.

True, an object would be better than a bool.

**Comment by domenic** [comment] 2016-02-11 15:01
> This is strange to me. Push rejects if permission is denied.

That's a shame.

> The TAG promises guide suggests that denied permission is a good case for rejection.

If you read it a bit further, the issue is more nuanced:

> - When it will be impossible to complete the requested task: for example if the operation is accessUsersContacts() and the user denies permission, then it should return a rejected promise.
>
> - When the operation is phrased as a question, and the answer is negative: for example if the operation is hasPermissionToAccessUsersContacts() and the user has denied permission, then it should return a promise fulfilled with false; it should not reject.
> 
> - APIs that are more ambiguous about being a question versus a demand: for example requestUsersContacts() could return a promise fulfilled with null if the user denies permission, or it could return a promise rejected with an error stating that the user denied permission.

I think this falls into the third category. The judgment call is how exceptional things are. A user denying permission for background sync seems unexceptional. Remember, rejections <-> exceptions, a correspondence which will be exact when using `async`/`await`. When writing the same code on e.g. Android, would you expect rejected permission to be handled with try/catch?

**Comment by domenic** [comment] 2016-02-11 15:05
> Rejecting feels like the right thing to do, we just need to do a good job of informing developers that they need to handle register rejections.

This is the exact opposite of how rejections/exceptions are meant to be used. If something needs to be handled, it should just be a return value. If it can bubble up the stack until some top-level handler deals with it, then an exception is appropriate.

**Comment by nicolassatragno** [comment] 2016-02-11 15:48
> > APIs that are more ambiguous about being a question versus a demand: for example requestUsersContacts() could return a promise fulfilled with null if the user denies permission, or it could return a promise rejected with an error stating that the user denied permission.

> I think this falls into the third category.

Except that in this case, the favourable path (i.e. the user did not block permission) does not involve returning any value, so we would have to artificially return something only to handle denying permission.

>> When it will be impossible to complete the requested task: for example if the operation is accessUsersContacts() and the user denies permission, then it should return a rejected promise.

If we determine what exactly should be blocked by a denied permission, we can tell if the task would be impossible to complete (disallow all sync registrations) or not (just don't run in the background), and therefore lean towards one side or the other.

> A user denying permission for background sync seems unexceptional

This is heavily influenced by how the UA implements the permission (is the user prompted? is it enabled by default?). As with push, these details can be defined in the spec. For example, if the UA has the feature enabled by default and the user is never prompted, we can expect rejecting permission to be an exceptional case.

**Comment by jakearchibald** [comment] 2016-02-15 16:09
@domenic 

> This is the exact opposite of how rejections/exceptions are meant to be used

Does this mean `fetch(url)` shouldn't reject on failure to fetch? Should `sync.register(…)` reject if there's a failure to save that sync record internally?

**Comment by annevk** [comment] 2016-02-15 16:31
Failure to fetch is an exceptional scenario, except perhaps when you invoke it from a service worker.

**Comment by jakearchibald** [comment] 2016-02-26 14:51
Been having a think about this. The method we're using here is `register`, which makes failure to register exceptional in the same way `keyValStore.set()` would be.

If it were `request` rather than `register`, I'd agree, it should resolve with a value indicating whether registration was successful or not.

We should integrate with the permissions API, which provides methods to query this stuff.

**Comment by mkruisselbrink** [comment] 2016-02-26 19:09
I tend to agree with @jakearchibald herre. This definitely falls into the more ambigious question vs. demand category. The `register` method currently doesn't return anything, and changing that just so we don't have to reject on permission failure seems very weird to me. And yes, I would expect permission denied to be a fairly exceptional situation, at least in chrome.

Furthermore rejecting the promise is more backwards compatible than just resolving with some value. Not much code using bgsync exists yet, so backwards compatibility might not matter much, but no existing code will be checking the value the promise resolves with, while existing code might be logging unhandled promise rejections, and thus people actually have a chance of noticing that things break.

**Comment by annevk** [comment] 2016-02-28 05:37
I don't see how the name of the method has much to do with it being exceptional or not. The question is whether it's common or not. And it seems definitely common for folks to deny this request. Thereby making it not exceptional.

**Comment by jakearchibald** [comment] 2016-02-29 10:31
@annevk with one-off sync the permission is opt-out, and doesn't make sense to be opt-in since that would be a regression on regular XHR/fetch. I don't think it will be common for this to fail.

But if this is the pattern we want, the method should be `request` and not `register`.

**Comment by annevk** [comment] 2016-02-29 10:42
If it indeed only does not work if the user went out of their way to disable the functionality and everyone is agreed on that model (I might have missed some discussion) then I agree failing would be exceptional (and likely the option to disable would disappear over time).

Does that mean we have resolved the timing questions? This will always happen when all tabs-are-closed whether online/offline?

**Comment by martinthomson** [comment] 2016-03-09 19:58
At @beverloo's request...

From a permissions perspective, I don't anticipate there being a user permission dialog in Firefox.  I don't know how you would talk to a user about this feature in a meaningful way (i.e., the same problem that caused periodic sync to be dropped).

I would like a better yardstick for deciding whether rejection is appropriate than the one we have here.  But, given the circumstances of this particular situation and the yardstick we have, I would say that not being granted permission would be exceptional so rejection is fine.

**Closed** 2016-03-15 12:12 UTC
